project:
  type: website
  output-dir: docs

website:
  title: "Muhd Hafiz' Portfolio Website"
  
  navbar:
    left:
      - href: page01-home.qmd
        text: Home
      - href: page02-gamedev.qmd
        text: NYP Projects
      - href: page03-projects.qmd
        text: Personal Projects
        
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-location: left
    
filters:
  - lightbox

lightbox: true

